import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JList;
import javax.swing.JOptionPane;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Asus
 */
public class GUI_Restoran_Home extends javax.swing.JFrame {

    /**
     * Creates new form GUI_Restoran_Home
     */
    public GUI_Restoran_Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfNamaMenu = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfHargaMenu = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnCreateMenu = new javax.swing.JButton();
        btnUpdateMenu = new javax.swing.JButton();
        btnDeleteMenu = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listNamaMenu = new javax.swing.JList<>();
        btnHome = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setEnabled(false);
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nama Menu");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 470, 109, 22);
        jPanel1.add(tfNamaMenu);
        tfNamaMenu.setBounds(190, 470, 380, 22);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Harga Menu");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 500, 111, 22);
        jPanel1.add(tfHargaMenu);
        tfHargaMenu.setBounds(220, 500, 352, 22);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Rp");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(190, 500, 24, 22);

        btnCreateMenu.setText("Create");
        btnCreateMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateMenuActionPerformed(evt);
            }
        });
        jPanel1.add(btnCreateMenu);
        btnCreateMenu.setBounds(20, 530, 71, 25);

        btnUpdateMenu.setText("Update");
        jPanel1.add(btnUpdateMenu);
        btnUpdateMenu.setBounds(100, 530, 73, 25);

        btnDeleteMenu.setText("Delete");
        jPanel1.add(btnDeleteMenu);
        btnDeleteMenu.setBounds(180, 530, 69, 25);

        jScrollPane1.setViewportView(listNamaMenu);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(14, 560, 748, 130);

        btnHome.setText("Logout");
        jPanel1.add(btnHome);
        btnHome.setBounds(690, 530, 71, 25);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rachmat Dwi Putra\\Downloads\\Ikuzo.png")); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(128, 2, 491, 441);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rachmat Dwi Putra\\Downloads\\PesanMakan.jpg")); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(-80, -80, 1050, 830);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCreateMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public String getNamaMenu(){
        return tfNamaMenu.getText();
    }
    
    public int getHargaMenu(){
        return Integer.parseInt(tfHargaMenu.getText());
    }
    
    public void setNamaMenu(String nama) {
        tfNamaMenu.setText(nama);
    }
    
    public void setHargaMenu (String s) {
        tfHargaMenu.setText(s);
    }

    public JButton getBtnCreateMenu() {
        return btnCreateMenu;
    }

    public JButton getBtnDeleteMenu() {
        return btnDeleteMenu;
    }

    public JButton getBtnUpdateMenu() {
        return btnUpdateMenu;
    }
    
    public JButton getBtnHome() {
        return btnHome;
    }
    
    public void setListMenu(String[] listMenu){
        listNamaMenu.setListData(listMenu);
    }
    
    public JList getListNamaMenu() {
        return listNamaMenu;
    }
    
    public String getSelectedMenu(){
        return listNamaMenu.getSelectedValue();
    }
    
    public void addActionListener(ActionListener al){
        btnCreateMenu.addActionListener(al);
        btnDeleteMenu.addActionListener(al);
        btnUpdateMenu.addActionListener(al);
        btnHome.addActionListener(al);
    }
    
    public void addMouseAdapter(MouseAdapter ma){
        listNamaMenu.addMouseListener(ma);
    }
    
    public void resetView(){
        tfHargaMenu.setText("");
        tfNamaMenu.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateMenu;
    private javax.swing.JButton btnDeleteMenu;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnUpdateMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listNamaMenu;
    private javax.swing.JTextField tfHargaMenu;
    private javax.swing.JTextField tfNamaMenu;
    // End of variables declaration//GEN-END:variables
}
