
import java.awt.event.ActionListener;
import javax.swing.JButton;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Asus
 */
public class GUI_Pelanggan_Login extends javax.swing.JFrame {

    /**
     * Creates new form GUI_Pelanggan_Login
     */
    public GUI_Pelanggan_Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pfPasswordPelangganLogin = new javax.swing.JPasswordField();
        tfIDPelangganLogin = new javax.swing.JTextField();
        btnLoginPelanggan = new javax.swing.JButton();
        btnKembaliLogin = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pfPasswordPelangganRegister = new javax.swing.JPasswordField();
        tfNamaPelangganRegister = new javax.swing.JTextField();
        tfIDPelangganRegister = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        taPelanggan = new javax.swing.JTextArea();
        btnDaftarPelanggan = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(null);

        jLabel4.setText("ID Pelanggan :");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(80, 90, 68, 20);

        jLabel5.setText("Password :");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(80, 130, 56, 15);
        jPanel2.add(pfPasswordPelangganLogin);
        pfPasswordPelangganLogin.setBounds(170, 130, 330, 19);
        jPanel2.add(tfIDPelangganLogin);
        tfIDPelangganLogin.setBounds(170, 90, 330, 19);

        btnLoginPelanggan.setText("Login");
        jPanel2.add(btnLoginPelanggan);
        btnLoginPelanggan.setBounds(400, 180, 109, 36);

        btnKembaliLogin.setText("Kembali");
        jPanel2.add(btnKembaliLogin);
        btnKembaliLogin.setBounds(20, 340, 92, 36);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/PesanMakan2.jpg"))); // NOI18N
        jPanel2.add(jLabel6);
        jLabel6.setBounds(0, 0, 610, 410);

        jTabbedPane1.addTab("Login", jPanel2);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("ID Pelanggan :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(70, 50, 100, 16);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("Nama Pelanggan :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(70, 90, 120, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("Password : ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(70, 130, 90, 16);

        pfPasswordPelangganRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pfPasswordPelangganRegisterActionPerformed(evt);
            }
        });
        jPanel1.add(pfPasswordPelangganRegister);
        pfPasswordPelangganRegister.setBounds(190, 130, 330, 19);

        tfNamaPelangganRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNamaPelangganRegisterActionPerformed(evt);
            }
        });
        jPanel1.add(tfNamaPelangganRegister);
        tfNamaPelangganRegister.setBounds(190, 90, 330, 19);

        tfIDPelangganRegister.setEditable(false);
        jPanel1.add(tfIDPelangganRegister);
        tfIDPelangganRegister.setBounds(190, 50, 330, 19);

        taPelanggan.setColumns(20);
        taPelanggan.setRows(5);
        jScrollPane1.setViewportView(taPelanggan);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(154, 225, 370, 152);

        btnDaftarPelanggan.setText("Daftar");
        jPanel1.add(btnDaftarPelanggan);
        btnDaftarPelanggan.setBounds(410, 165, 114, 42);

        btnKembali.setText("Kembali");
        jPanel1.add(btnKembali);
        btnKembali.setBounds(12, 350, 86, 42);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/PesanMakan3.jpg"))); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(-210, -140, 840, 690);

        jTabbedPane1.addTab("Register", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pfPasswordPelangganRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfPasswordPelangganRegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pfPasswordPelangganRegisterActionPerformed

    private void tfNamaPelangganRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNamaPelangganRegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNamaPelangganRegisterActionPerformed

    /**
     * @param args the command line arguments
     */
    
    //TextField
    public void setIdRegister(int id) {
        tfIDPelangganRegister.setText("C-"+id);
    }
    
    public String getIdRegister() {
        return tfIDPelangganRegister.getText();
    }
    
    public String getNama() {
        return tfNamaPelangganRegister.getText();
    }
    
    public String getIdLogin() {
        return tfIDPelangganLogin.getText();
    }
    
    //PasswordField
    
    public String getPassRegister() {
        return pfPasswordPelangganRegister.getText();
    }
    
    public String getPassLogin() {
        return pfPasswordPelangganLogin.getText();
    }
    
    //Button Getter
    public JButton getBtnDaftarPelanggan() {
        return btnDaftarPelanggan;
    }
    
    public JButton getBtnLoginPelanggan() {
        return btnLoginPelanggan;
    }
    
    public JButton getBtnKembali() {
        return btnKembali;
    }
    
    public JButton getBtnKembaliLogin() {
        return btnKembaliLogin;
    }
    
    //TextArea Setter
    public void setTextRegister(String s) {
        taPelanggan.setText(s);
    }
    
    //Misc
    public void addActionListener(ActionListener x) {
        btnDaftarPelanggan.addActionListener(x);
        btnLoginPelanggan.addActionListener(x);
        btnKembali.addActionListener(x);
        btnKembaliLogin.addActionListener(x);
    }
    
    public void resetView() {
        tfNamaPelangganRegister.setText("");
        pfPasswordPelangganRegister.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDaftarPelanggan;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnKembaliLogin;
    private javax.swing.JButton btnLoginPelanggan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPasswordField pfPasswordPelangganLogin;
    private javax.swing.JPasswordField pfPasswordPelangganRegister;
    private javax.swing.JTextArea taPelanggan;
    private javax.swing.JTextField tfIDPelangganLogin;
    private javax.swing.JTextField tfIDPelangganRegister;
    private javax.swing.JTextField tfNamaPelangganRegister;
    // End of variables declaration//GEN-END:variables
}
