
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import javax.swing.JButton;
import javax.swing.JList;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author USER
 */
public class GUI_Aplikasi extends javax.swing.JFrame {

    /**
     * Creates new form GUI_Aplikasi
     */
    public GUI_Aplikasi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taAplikasi = new javax.swing.JTextArea();
        btnPelanggan = new javax.swing.JButton();
        btnDriver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnRestoran = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);

        taAplikasi.setColumns(20);
        taAplikasi.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        taAplikasi.setRows(2);
        taAplikasi.setText("       Selamat Datang di IKUZO!\n      Silahkan Pilih Menu Login.");
        jScrollPane1.setViewportView(taAplikasi);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(155, 28, 363, 78);

        btnPelanggan.setFont(new java.awt.Font("Comic Sans MS", 2, 20)); // NOI18N
        btnPelanggan.setText("Pelanggan");
        jPanel1.add(btnPelanggan);
        btnPelanggan.setBounds(102, 589, 132, 56);

        btnDriver.setFont(new java.awt.Font("Comic Sans MS", 2, 20)); // NOI18N
        btnDriver.setText("Driver");
        jPanel1.add(btnDriver);
        btnDriver.setBounds(270, 589, 132, 56);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Ikuzo.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1.setMaximumSize(new java.awt.Dimension(120, 120));
        jLabel1.setMinimumSize(new java.awt.Dimension(120, 120));
        jLabel1.setPreferredSize(new java.awt.Dimension(120, 120));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(80, 119, 500, 450);

        btnRestoran.setFont(new java.awt.Font("Comic Sans MS", 2, 20)); // NOI18N
        btnRestoran.setText("Restoran");
        btnRestoran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestoranActionPerformed(evt);
            }
        });
        jPanel1.add(btnRestoran);
        btnRestoran.setBounds(435, 589, 132, 56);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/PesanMakan.jpg"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(-30, -70, 830, 830);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 687, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRestoranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestoranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRestoranActionPerformed

    /**
     * @param args the command line arguments
     */
    public JButton getBtnPelanggan() {
        return btnPelanggan;
    }
    
    public JButton getBtnDriver() {
        return btnDriver;
    }
    
    public JButton getBtnRestoran() {
        return btnRestoran;
    }
    
    public void addActionListener(ActionListener al){
        btnRestoran.addActionListener(al);
        btnPelanggan.addActionListener(al);
        btnDriver.addActionListener(al);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDriver;
    private javax.swing.JButton btnPelanggan;
    private javax.swing.JButton btnRestoran;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea taAplikasi;
    // End of variables declaration//GEN-END:variables
}
