
import java.awt.event.ActionListener;
import javax.swing.JButton;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Asus
 */
public class GUI_Pengemudi_Login extends javax.swing.JFrame {

    /**
     * Creates new form GUI_Pengemudi_Login
     */
    public GUI_Pengemudi_Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pfPasswordPengemudiLogin = new javax.swing.JPasswordField();
        tfIDPengemudiLogin = new javax.swing.JTextField();
        btnLoginPengemudi = new javax.swing.JButton();
        btnKembaliLogin = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfIDPengemudiRegister = new javax.swing.JTextField();
        tfNamaPengemudiRegister = new javax.swing.JTextField();
        btnDaftarPengemudi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taPengemudiRegister = new javax.swing.JTextArea();
        pfPasswordPengemudiRegister = new javax.swing.JPasswordField();
        btnKembali = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        tfPlat = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setText("ID Pengemudi :");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(59, 61, 97, 16);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setText("Password :");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(59, 121, 72, 16);

        pfPasswordPengemudiLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pfPasswordPengemudiLoginActionPerformed(evt);
            }
        });
        jPanel3.add(pfPasswordPengemudiLogin);
        pfPasswordPengemudiLogin.setBounds(202, 118, 330, 22);
        jPanel3.add(tfIDPengemudiLogin);
        tfIDPengemudiLogin.setBounds(202, 58, 330, 22);

        btnLoginPengemudi.setText("Login");
        btnLoginPengemudi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginPengemudiActionPerformed(evt);
            }
        });
        jPanel3.add(btnLoginPengemudi);
        btnLoginPengemudi.setBounds(445, 158, 87, 37);

        btnKembaliLogin.setText("Kembali");
        jPanel3.add(btnKembaliLogin);
        btnKembaliLogin.setBounds(12, 365, 90, 37);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rachmat Dwi Putra\\Downloads\\PesanMakan4.jpg")); // NOI18N
        jPanel3.add(jLabel7);
        jLabel7.setBounds(-270, -160, 910, 780);

        jTabbedPane1.addTab("Login", jPanel3);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("ID Pengemudi :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(58, 44, 97, 16);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("Nama Pengemudi :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(58, 90, 118, 16);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("Plat Nomor :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(58, 177, 79, 16);

        tfIDPengemudiRegister.setEditable(false);
        jPanel1.add(tfIDPengemudiRegister);
        tfIDPengemudiRegister.setBounds(200, 41, 361, 22);
        jPanel1.add(tfNamaPengemudiRegister);
        tfNamaPengemudiRegister.setBounds(200, 87, 361, 22);

        btnDaftarPengemudi.setText("Daftar");
        btnDaftarPengemudi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDaftarPengemudiActionPerformed(evt);
            }
        });
        jPanel1.add(btnDaftarPengemudi);
        btnDaftarPengemudi.setBounds(440, 209, 121, 42);

        taPengemudiRegister.setColumns(20);
        taPengemudiRegister.setRows(5);
        jScrollPane1.setViewportView(taPengemudiRegister);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(181, 258, 380, 157);
        jPanel1.add(pfPasswordPengemudiRegister);
        pfPasswordPengemudiRegister.setBounds(200, 134, 361, 22);

        btnKembali.setText("Kembali");
        jPanel1.add(btnKembali);
        btnKembali.setBounds(12, 366, 107, 49);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setText("Password :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(58, 137, 72, 16);
        jPanel1.add(tfPlat);
        tfPlat.setBounds(200, 174, 361, 22);

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rachmat Dwi Putra\\Downloads\\PesanMakan.jpg")); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(-300, -130, 1230, 630);

        jTabbedPane1.addTab("Register", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDaftarPengemudiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaftarPengemudiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDaftarPengemudiActionPerformed

    private void pfPasswordPengemudiLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfPasswordPengemudiLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pfPasswordPengemudiLoginActionPerformed

    private void btnLoginPengemudiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginPengemudiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLoginPengemudiActionPerformed

    /**
     * @param args the command line arguments
     */
    
    //TextField
    public void setIdRegister(int id) {
        tfIDPengemudiRegister.setText("D-"+id);
    }
    
    public String getIdRegister() {
        return tfIDPengemudiRegister.getText();
    }
    
    public String getNama() {
        return tfNamaPengemudiRegister.getText();
    }
    
    public String getIdLogin() {
        return tfIDPengemudiLogin.getText();
    }
    
    public String getPlatNomor() {
        return tfPlat.getText();
    }
    
    //PasswordField
    public String getPassRegister() {
        return pfPasswordPengemudiRegister.getText();
    }
    
    public String getPassLogin() {
        return pfPasswordPengemudiLogin.getText();
    }
    
    //Button Getter
    public JButton getBtnDaftar() {
        return btnDaftarPengemudi;
    }
    
    public JButton getBtnLogin() {
        return btnLoginPengemudi;
    }
    
    public JButton getBtnKembali() {
        return btnKembali;
    }
    
    public JButton getBtnKembaliLogin() {
        return btnKembaliLogin;
    }
    
    //TextArea Setter
    public void setTextRegister(String s) {
        taPengemudiRegister.setText(s);
    }
    
    //Misc
    public void addActionListener(ActionListener x) {
        btnDaftarPengemudi.addActionListener(x);
        btnLoginPengemudi.addActionListener(x);
        btnKembali.addActionListener(x);
        btnKembaliLogin.addActionListener(x);
    }
    
    public void resetView() {
        tfNamaPengemudiRegister.setText("");
        tfPlat.setText("");
        pfPasswordPengemudiRegister.setText("");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDaftarPengemudi;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnKembaliLogin;
    private javax.swing.JButton btnLoginPengemudi;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JPasswordField pfPasswordPengemudiLogin;
    private javax.swing.JPasswordField pfPasswordPengemudiRegister;
    private javax.swing.JTextArea taPengemudiRegister;
    private javax.swing.JTextField tfIDPengemudiLogin;
    private javax.swing.JTextField tfIDPengemudiRegister;
    private javax.swing.JTextField tfNamaPengemudiRegister;
    private javax.swing.JTextField tfPlat;
    // End of variables declaration//GEN-END:variables
}
