
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import javax.swing.JButton;
import javax.swing.JList;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Asus
 */
public class GUI_Restoran_Login extends javax.swing.JFrame {

    /**
     * Creates new form GUI_Restoran
     */
    public GUI_Restoran_Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pfPasswordRestoLogin = new javax.swing.JPasswordField();
        tfIDRestoLogin = new javax.swing.JTextField();
        btnRestoLogin = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        Resto_Register = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfIDRestoranRegister = new javax.swing.JTextField();
        tfNamaRestoran = new javax.swing.JTextField();
        btnDaftarResto = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        pfPasswordRestoRegister = new javax.swing.JPasswordField();
        jScrollPane1 = new javax.swing.JScrollPane();
        taResto = new javax.swing.JTextArea();
        btnHome = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel1.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setText("ID Restoran :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(70, 54, 87, 16);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setText("Password :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(70, 116, 72, 16);
        jPanel1.add(pfPasswordRestoLogin);
        pfPasswordRestoLogin.setBounds(213, 113, 298, 22);
        jPanel1.add(tfIDRestoLogin);
        tfIDRestoLogin.setBounds(213, 51, 298, 22);

        btnRestoLogin.setText("Login");
        jPanel1.add(btnRestoLogin);
        btnRestoLogin.setBounds(393, 176, 118, 38);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rachmat Dwi Putra\\Downloads\\PesanMakan3.jpg")); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(-200, -130, 900, 690);

        jTabbedPane1.addTab("Login", jPanel1);

        Resto_Register.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Resto_Register.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("Nama Restoran :");
        Resto_Register.add(jLabel1);
        jLabel1.setBounds(50, 80, 108, 16);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("Password :");
        Resto_Register.add(jLabel2);
        jLabel2.setBounds(50, 110, 77, 25);

        tfIDRestoranRegister.setEditable(false);
        tfIDRestoranRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIDRestoranRegisterActionPerformed(evt);
            }
        });
        Resto_Register.add(tfIDRestoranRegister);
        tfIDRestoranRegister.setBounds(180, 34, 341, 22);
        Resto_Register.add(tfNamaRestoran);
        tfNamaRestoran.setBounds(180, 70, 342, 22);

        btnDaftarResto.setText("Daftar");
        btnDaftarResto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDaftarRestoActionPerformed(evt);
            }
        });
        Resto_Register.add(btnDaftarResto);
        btnDaftarResto.setBounds(410, 150, 113, 34);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("ID Restoran :");
        Resto_Register.add(jLabel3);
        jLabel3.setBounds(53, 32, 87, 26);
        Resto_Register.add(pfPasswordRestoRegister);
        pfPasswordRestoRegister.setBounds(180, 110, 342, 22);

        taResto.setEditable(false);
        taResto.setColumns(20);
        taResto.setRows(5);
        jScrollPane1.setViewportView(taResto);

        Resto_Register.add(jScrollPane1);
        jScrollPane1.setBounds(137, 194, 384, 152);

        btnHome.setText("Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        Resto_Register.add(btnHome);
        btnHome.setBounds(13, 365, 113, 34);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rachmat Dwi Putra\\Downloads\\PesanMakan2.jpg")); // NOI18N
        Resto_Register.add(jLabel6);
        jLabel6.setBounds(0, -30, 670, 460);

        jTabbedPane1.addTab("Register", Resto_Register);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfIDRestoranRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIDRestoranRegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIDRestoranRegisterActionPerformed

    private void btnDaftarRestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaftarRestoActionPerformed
        
    }//GEN-LAST:event_btnDaftarRestoActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public String getRestoIdRegister() {
        return tfIDRestoranRegister.getText();
    }

    public void setRestoIdRegister(int id) {
        tfIDRestoranRegister.setText("R-" + id);
    }

    public String getRestoName() {
        return tfNamaRestoran.getText();
    }

    public String getPassRestoRegister() {
        return pfPasswordRestoRegister.getText();
    }

    public String getRestoIdLogin() {
        return tfIDRestoLogin.getText();
    }

    public String getPassRestoLogin() {
        return pfPasswordRestoLogin.getText();
    }

    public JButton getBtnLoginResto() {
        return btnRestoLogin;
    }

    public JButton getBtnHome() {
        return btnHome;
    }

    public JButton getBtnDaftarResto() {
        return btnDaftarResto;
    }

    public void addActionListener(ActionListener al) {
        btnDaftarResto.addActionListener(al);
        btnRestoLogin.addActionListener(al);
        btnHome.addActionListener(al);
    }

    public void resetView() {
        tfNamaRestoran.setText("");
        pfPasswordRestoRegister.setText("");
    }
    
    public void setRestoString(String s){
        taResto.setText(s);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Resto_Register;
    private javax.swing.JButton btnDaftarResto;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnRestoLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPasswordField pfPasswordRestoLogin;
    private javax.swing.JPasswordField pfPasswordRestoRegister;
    private javax.swing.JTextArea taResto;
    private javax.swing.JTextField tfIDRestoLogin;
    private javax.swing.JTextField tfIDRestoranRegister;
    private javax.swing.JTextField tfNamaRestoran;
    // End of variables declaration//GEN-END:variables
}
